SELECT NOMCLIENT,PRENOMCLIENT
FROM CLIENTS
WHERE IDCLIENT NOT IN (SELECT IDCLIENT FROM LOCATIONS);

SELECT NOMCLIENT,PRENOMCLIENT
FROM CLIENTS c
WHERE NOT EXISTS (SELECT * FROM LOCATIONS l
                    WHERE c.IDCLIENT=l.IDCLIENT);

SELECT NOMCLIENT, PRENOMCLIENT
FROM CLIENTS
MINUS
SELECT NOMCLIENT, PRENOMCLIENT
FROM CLIENTS JOIN LOCATIONS L on CLIENTS.IDCLIENT = L.IDCLIENT

SELECT NOMCAMPING
FROM CAMPINGS c
WHERE NOT EXISTS(
    SELECT * FROM BUNGALOWS b WHERE c.IDCAMPING=b.IDCAMPING
    AND SUPERFICIEBUNGALOW>50
    );

SELECT COUNT(IDCLIENT)
FROM LOCATIONS l
WHERE NOT EXISTS(
    SELECT * FROM LOCATIONS l2 WHERE l.IDCLIENT=l2.IDCLIENT
    AND l2.MONTANTLOCATION<990
    );

SELECT NOMCLIENT
FROM CLIENTS c
WHERE PRENOMCLIENT LIKE 'J%'
AND NOT EXISTS(
    SELECT * FROM CAMPINGS ca WHERE c.villeClient=ca.VILLECAMPING);

SELECT DISTINCT CATEGORIESERVICE
FROM SERVICES s
WHERE NOT EXISTS(
    SELECT * FROM CAMPINGS JOIN BUNGALOWS B on CAMPINGS.IDCAMPING = B.IDCAMPING
                           JOIN PROPOSER P on B.IDBUNGALOW = P.IDBUNGALOW
                           JOIN SERVICES S2 on S2.IDSERVICE = P.IDSERVICE
    WHERE s.CATEGORIESERVICE=S2.CATEGORIESERVICE
    AND NOMCAMPING = 'La Décharge Monochrome'
);

SELECT NOMEMPLOYE
FROM EMPLOYES
WHERE IDCAMPING is null;

SELECT CATEGORIESERVICE, COUNT(*)
FROM SERVICES
group by CATEGORIESERVICE;

SELECT VILLECLIENT
FROM CLIENTS
GROUP BY VILLECLIENT
HAVING COUNT(IDCLIENT)>=3

SELECT NOMCAMPING ,AVG(SALAIREEMPLOYE)
FROM CAMPINGS JOIN EMPLOYES E on CAMPINGS.IDCAMPING = E.IDCAMPING
GROUP BY NOMCAMPING

SELECT NOMCAMPING
FROM CAMPINGS JOIN EMPLOYES E on CAMPINGS.IDCAMPING = E.IDCAMPING
GROUP BY NOMCAMPING
HAVING COUNT(IDEMPLOYE)>3;

SELECT NOMCLIENT,PRENOMCLIENT, COUNT(IDLOCATION)
FROM CLIENTS JOIN LOCATIONS L on CLIENTS.IDCLIENT = L.IDCLIENT
GROUP BY NOMCLIENT, PRENOMCLIENT,L.IDCLIENT
ORDER BY count(IDLOCATION) DESC;

SELECT NOMCAMPING
FROM CAMPINGS JOIN EMPLOYES E on CAMPINGS.IDCAMPING = E.IDCAMPING
GROUP BY NOMCAMPING
HAVING AVG(SALAIREEMPLOYE)>1400;

SELECT NOMCLIENT,PRENOMCLIENT
FROM CLIENTS
WHERE IDCLIENT IN (
SELECT IDCLIENT
FROM LOCATIONS JOIN BUNGALOWS B on B.IDBUNGALOW = LOCATIONS.IDBUNGALOW
GROUP BY IDCLIENT
HAVING count(Distinct IDCAMPING)=2);

SELECT NOMBUNGALOW, count(IDSERVICE) as "nb service"
FROM BUNGALOWS left join PROPOSER P on BUNGALOWS.IDBUNGALOW = P.IDBUNGALOW
GROUP BY NOMBUNGALOW, P.IDBUNGALOW
ORDER BY count(IDSERVICE) desc

SELECT NOMCAMPING
FROM CAMPINGS JOIN BUNGALOWS B on CAMPINGS.IDCAMPING = B.IDCAMPING
WHERE SUPERFICIEBUNGALOW<65
GROUP BY NOMCAMPING
ORDER BY count(IDBUNGALOW);

SELECT NOMCAMPING
FROM CAMPINGS JOIN EMPLOYES E on CAMPINGS.IDCAMPING = E.IDCAMPING
GROUP BY NOMCAMPING
HAVING min(SALAIREEMPLOYE)>=1000;

R66
SELECT NOMBUNGALOW
FROM BUNGALOWS JOIN PROPOSER P on BUNGALOWS.IDBUNGALOW = P.IDBUNGALOW
GROUP BY P.IDBUNGALOW,NOMBUNGALOW
HAVING COUNT(IDSERVICE) = (SELECT COUNT(IDSERVICE) FROM BUNGALOWS JOIN PROPOSER P2 on BUNGALOWS.IDBUNGALOW = P2.IDBUNGALOW WHERE NOMBUNGALOW='Le Royal');

R67
SELECT BUNGALOWS.NOMBUNGALOW,COUNT(IDLOCATION)FROM BUNGALOWS LEFT JOIN LOCATIONS L on BUNGALOWS.IDBUNGALOW = L.IDBUNGALOW
                                              JOIN CAMPINGS C2 on C2.IDCAMPING = BUNGALOWS.IDCAMPING
                                              WHERE NOMCAMPING='La Décharge Monochrome'
                                              group by BUNGALOWS.NOMBUNGALOW
ORDER BY COUNT(IDLOCATION) DESC;

R68
SELECT NOMCLIENT, PRENOMCLIENT
FROM CLIENTS JOIN LOCATIONS L on CLIENTS.IDCLIENT = L.IDCLIENT
GROUP BY L.IDCLIENT, NOMCLIENT, PRENOMCLIENT
HAVING AVG(MONTANTLOCATION)> 1100 AND count(IDLOCATION)>1

R69
SELECT NOMBUNGALOW
FROM BUNGALOWS JOIN PROPOSER P on BUNGALOWS.IDBUNGALOW = P.IDBUNGALOW
GROUP BY P.IDBUNGALOW, NOMBUNGALOW
HAVING COUNT(IDSERVICE)= (SELECT MAX(COUNT(IDSERVICE)) FROM PROPOSER GROUP BY IDBUNGALOW)

R70
SELECT VILLECAMPING, COUNT(IDCAMPING)
FROM CAMPINGS
GROUP BY VILLECAMPING

R71
SELECT NOMCAMPING
FROM CAMPINGS JOIN EMPLOYES E on CAMPINGS.IDCAMPING = E.IDCAMPING
GROUP BY NOMCAMPING
HAVING COUNT(IDEMPLOYE)>3;

R72
SELECT NOMCAMPING,COUNT(IDEMPLOYE)
FROM CAMPINGS LEFT JOIN EMPLOYES E on CAMPINGS.IDCAMPING = E.IDCAMPING
GROUP BY NOMCAMPING
ORDER BY(COUNT(IDEMPLOYE)) DESC;

R73
SELECT NOMSERVICE, COUNT(DISTINCT(IDCAMPING))
FROM SERVICES JOIN PROPOSER P on SERVICES.IDSERVICE = P.IDSERVICE
JOIN BUNGALOWS B on B.IDBUNGALOW = P.IDBUNGALOW
WHERE CATEGORIESERVICE='Luxe'
GROUP BY NOMSERVICE;

R74
SELECT NOMCLIENT,PRENOMCLIENT
FROM CLIENTS JOIN LOCATIONS L on CLIENTS.IDCLIENT = L.IDCLIENT
GROUP BY NOMCLIENT, PRENOMCLIENT, CLIENTS.IDCLIENT
HAVING COUNT(IDLOCATION)= (SELECT MAX(COUNT(IDLOCATION)) FROM LOCATIONS GROUP BY LOCATIONS.IDCLIENT)

R80
SELECT DISTINCT(NOMBUNGALOW) FROM BUNGALOWS JOIN LOCATIONS L on BUNGALOWS.IDBUNGALOW = L.IDBUNGALOW
JOIN PROPOSER P on BUNGALOWS.IDBUNGALOW = P.IDBUNGALOW
JOIN SERVICES S on S.IDSERVICE = P.IDSERVICE
WHERE NOMSERVICE='Kit de Bain'

R81
SELECT NOMBUNGALOW FROM BUNGALOWS WHERE IDBUNGALOW=(SELECT IDBUNGALOW FROM LOCATIONS
GROUP BY IDBUNGALOW
HAVING COUNT(IDLOCATION)>4);

R82
SELECT COUNT(IDCLIENT)
FROM CLIENTS
WHERE VILLECLIENT NOT IN (SELECT VILLECAMPING FROM CAMPINGS)

R83
SELECT NOMBUNGALOW, COUNT(IDSERVICE)
FROM BUNGALOWS LEFT JOIN PROPOSER P on BUNGALOWS.IDBUNGALOW = P.IDBUNGALOW
JOIN CAMPINGS C2 on C2.IDCAMPING = BUNGALOWS.IDCAMPING
WHERE NOMCAMPING='La Décharge Monochrome'
GROUP BY P.IDBUNGALOW, NOMBUNGALOW
ORDER BY COUNT(IDSERVICE);

R84
SELECT NOMBUNGALOW FROM BUNGALOWS JOIN CAMPINGS C2 on C2.IDCAMPING = BUNGALOWS.IDCAMPING
WHERE NOMCAMPING ='Les Flots Bleus'
AND SUPERFICIEBUNGALOW=(SELECT MIN(SUPERFICIEBUNGALOW)FROM BUNGALOWS JOIN CAMPINGS C3 on C3.IDCAMPING = BUNGALOWS.IDCAMPING WHERE NOMCAMPING ='Les Flots Bleus'
 )

R85
SELECT NOMBUNGALOW
FROM BUNGALOWS JOIN LOCATIONS L on BUNGALOWS.IDBUNGALOW = L.IDBUNGALOW
JOIN PROPOSER P on BUNGALOWS.IDBUNGALOW = P.IDBUNGALOW
GROUP BY NOMBUNGALOW, L.IDBUNGALOW
HAVING COUNT(IDSERVICE)>1 AND COUNT(IDLOCATION)>1;

R100
SELECT NOMBUNGALOW
FROM BUNGALOWS
WHERE NOT EXISTS ( SELECT IDSERVICE FROM SERVICES
                    MINUS
                    SELECT IDSERVICE FROM PROPOSER
                    WHERE PROPOSER.IDBUNGALOW=BUNGALOWS.IDBUNGALOW)

R101
SELECT NOMBUNGALOW
FROM BUNGALOWS
WHERE NOT EXISTS ( SELECT IDSERVICE FROM SERVICES WHERE CATEGORIESERVICE='Luxe'
                    MINUS
                    SELECT IDSERVICE FROM PROPOSER
                    WHERE PROPOSER.IDBUNGALOW=BUNGALOWS.IDBUNGALOW)

R102
SELECT NOMBUNGALOW
FROM BUNGALOWS
WHERE NOT EXISTS ( SELECT SERVICES.IDSERVICE FROM SERVICES join PROPOSER P on SERVICES.IDSERVICE = P.IDSERVICE
                                    join GOZZOG.BUNGALOWS B on B.IDBUNGALOW = P.IDBUNGALOW
                                    WHERE B.NOMBUNGALOW='La Poubelle'
                    MINUS
                    SELECT IDSERVICE FROM PROPOSER
                    WHERE PROPOSER.IDBUNGALOW=BUNGALOWS.IDBUNGALOW)

R103
SELECT DISTINCT(NOMCLIENT)
FROM CLIENTS JOIN LOCATIONS L on CLIENTS.IDCLIENT = L.IDCLIENT
WHERE NOT EXISTS( SELECT VILLECAMPING FROM CAMPINGS
                                      MINUS
                SELECT V.VILLECAMPING FROM CAMPINGS V JOIN BUNGALOWS B on V.IDCAMPING = B.IDCAMPING JOIN LOCATIONS L2 on B.IDBUNGALOW = L2.IDBUNGALOW
                                      WHERE L.IDCLIENT=L2.IDCLIENT)

R104
SELECT DISTINCT(NOMCLIENT)
FROM CLIENTS JOIN LOCATIONS L on CLIENTS.IDCLIENT = L.IDCLIENT
WHERE NOT EXists( SELECT IDBUNGALOW FROM LOCATIONS JOIN CLIENTS C2 on LOCATIONS.IDCLIENT = C2.IDCLIENT
                                    WHERE C2.NOMCLIENT='Zeblouse'
                                    AND C2.PRENOMCLIENT='Agathe'
                                    MINUS
                                    SELECT IDBUNGALOW FROM LOCATIONS
                                                      WHERE L.IDCLIENT=LOCATIONS.IDCLIENT)

R105
SELECT DISTINCT (NOMCLIENT),PRENOMCLIENT
FROM CLIENTS
WHERE NOT EXISTS( SELECT IDCAMPING FROM BUNGALOWS JOIN LOCATIONS L on BUNGALOWS.IDBUNGALOW = L.IDBUNGALOW
                                   WHERE L.IDCLIENT=(SELECT IDCLIENT FROM CLIENTS WHERE NOMCLIENT='Zeblouse' AND PRENOMCLIENT='Agathe')
                                   MINUS
                  SELECT B.IDCAMPING FROM BUNGALOWS B JOIN LOCATIONS L2 on B.IDBUNGALOW = L2.IDBUNGALOW
                                   WHERE L2.IDCLIENT=CLIENTS.IDCLIENT)
AND NOT EXISTS(SELECT B.IDCAMPING FROM BUNGALOWS B JOIN LOCATIONS L2 on B.IDBUNGALOW = L2.IDBUNGALOW
                                   WHERE L2.IDCLIENT=CLIENTS.IDCLIENT
                                   MINUS
                  SELECT IDCAMPING FROM BUNGALOWS JOIN LOCATIONS L on BUNGALOWS.IDBUNGALOW = L.IDBUNGALOW
                                                                      WHERE L.IDCLIENT=(SELECT IDCLIENT FROM CLIENTS WHERE NOMCLIENT='Zeblouse' AND PRENOMCLIENT='Agathe'))

R110
SELECT NOMSERVICE
FROM SERVICES
WHERE NOT EXISTS( SELECT IDBUNGALOW FROM BUNGALOWS WHERE SUPERFICIEBUNGALOW>60
                        MINUS
                   SELECT IDBUNGALOW FROM PROPOSER WHERE PROPOSER.IDSERVICE=SERVICES.IDSERVICE)

R111
SELECT IDCLIENT, NOMCLIENT,PRENOMCLIENT
FROM CLIENTS
WHERE NOT EXISTS(SELECT C.IDCLIENT FROM CLIENTS C JOIN LOCATIONS L on C.IDCLIENT = L.IDCLIENT
                                 JOIN BUNGALOWS B on B.IDBUNGALOW = L.IDBUNGALOW
                                 JOIN CAMPINGS C2 on C2.IDCAMPING = B.IDCAMPING
                                 WHERE VILLECAMPING='Palavas'
                                 AND C.IDCLIENT=CLIENTS.IDCLIENT)

R112
SELECT NOMSERVICE FROM SERVICES WHERE IDSERVICE IN(
SELECT IDSERVICE FROM PROPOSER WHERE EXISTS(SELECT IDBUNGALOW FROM BUNGALOWS JOIN CAMPINGS C2 on BUNGALOWS.IDCAMPING = C2.IDCAMPING
WHERE NOMCAMPING='Les Flots Bleus'
AND SUPERFICIEBUNGALOW=(SELECT MAX(SUPERFICIEBUNGALOW) FROM BUNGALOWS JOIN CAMPINGS C3 on C3.IDCAMPING = BUNGALOWS.IDCAMPING WHERE NOMCAMPING='Les Flots Bleus')
AND PROPOSER.IDBUNGALOW=BUNGALOWS.IDBUNGALOW));

R113
SELECT E.NOMEMPLOYE,E.PRENOMEMPLOYE,COUNT(E2.IDEMPLOYE)
FROM EMPLOYES E LEFT JOIN EMPLOYES E2 ON E.IDEMPLOYE=E2.IDEMPLOYECHEF
JOIN CAMPINGS C2 on C2.IDCAMPING = E.IDCAMPING
WHERE NOMCAMPING='La Décharge Monochrome'
GROUP BY E.IDEMPLOYE,E.NOMEMPLOYE, E.PRENOMEMPLOYE

R114
SELECT NOMCAMPING
FROM CAMPINGS
WHERE NOT EXISTS( SELECT IDCAMPING FROM BUNGALOWS WHERE SUPERFICIEBUNGALOW<=50
                                                  AND CAMPINGS.IDCAMPING=BUNGALOWS.IDCAMPING)

R115
SELECT NOMCLIENT
FROM CLIENTS JOIN LOCATIONS L on CLIENTS.IDCLIENT = L.IDCLIENT
GROUP BY L.IDCLIENT,PRENOMCLIENT,NOMCLIENT
HAVING COUNT(IDLOCATION)=(SELECT COUNT(IDLOCATION) FROM LOCATIONS JOIN GOZZOG.CLIENTS C2 on C2.IDCLIENT = LOCATIONS.IDCLIENT WHERE C2.NOMCLIENT='Zeblouse' AND C2.PRENOMCLIENT='Agathe')

R116
SELECT NOMSERVICE FROM SERVICES JOIN PROPOSER P on SERVICES.IDSERVICE = P.IDSERVICE
GROUP BY NOMSERVICE
HAVING COUNT(P.IDSERVICE)<5;

R117
SELECT C2.NOMCAMPING FROM EMPLOYES JOIN CAMPINGS C2 on C2.IDCAMPING = EMPLOYES.IDCAMPING
GROUP BY C2.IDCAMPING,NOMCAMPING
HAVING COUNT(IDEMPLOYE)=(SELECT MAX(COUNT(IDEMPLOYE)) FROM EMPLOYES JOIN CAMPINGS C2 on C2.IDCAMPING = EMPLOYES.IDCAMPING
GROUP BY C2.IDCAMPING)

R118
SELECT NOMBUNGALOW FROM BUNGALOWS JOIN PROPOSER P on BUNGALOWS.IDBUNGALOW = P.IDBUNGALOW JOIN SERVICES S on S.IDSERVICE = P.IDSERVICE
GROUP BY NOMBUNGALOW,P.IDBUNGALOW
HAVING COUNT(DISTINCT S.CATEGORIESERVICE )=(SELECT COUNT(DISTINCT S2.CATEGORIESERVICE) FROM SERVICES S2);

R119
SELECT DISTINCT NOMBUNGALOW FROM BUNGALOWS B2 JOIN PROPOSER P on B2.IDBUNGALOW = P.IDBUNGALOW
WHERE NOT EXISTS(
    SELECT P2.IDBUNGALOW FROM PROPOSER P2
    WHERE P2.IDBUNGALOW=B2.IDBUNGALOW
    AND NOT exists(SELECT P3.IDSERVICE FROM PROPOSER P3 JOIN BUNGALOWS B on B.IDBUNGALOW = P3.IDBUNGALOW WHERE B.NOMBUNGALOW='La Suite Régalienne' AND P2.IDSERVICE=P3.IDSERVICE)
)
GROUP BY NOMBUNGALOW, P.IDBUNGALOW
HAVING COUNT(P.IDBUNGALOW)=(SELECT COUNT(P4.IDBUNGALOW) FROM PROPOSER P4 JOIN BUNGALOWS B3 on B3.IDBUNGALOW = P4.IDBUNGALOW WHERE B3.NOMBUNGALOW='La Suite Régalienne')

R120
SELECT NOMBUNGALOW
FROM BUNGALOWS JOIN CAMPINGS C2 on C2.IDCAMPING = BUNGALOWS.IDCAMPING
WHERE SUPERFICIEBUNGALOW>(SELECT AVG(SUPERFICIEBUNGALOW) FROM BUNGALOWS JOIN CAMPINGS C3 on C3.IDCAMPING = BUNGALOWS.IDCAMPING
                                                           WHERE C2.IDCAMPING=C3.IDCAMPING)

R121
SELECT NOMBUNGALOW, COUNT(IDLOCATION) as r
FROM BUNGALOWS LEFT JOIN LOCATIONS L on BUNGALOWS.IDBUNGALOW = L.IDBUNGALOW
WHERE DATEDEBUT<='30/06/2021'
AND DATEFIN>= '01/06/2021'
group by NOMBUNGALOW
UNION
SELECT B.NOMBUNGALOW,0
FROM BUNGALOWS B
WHERE B.IDBUNGALOW NOT IN(
    SELECT BUNGALOWS.IDBUNGALOW
FROM BUNGALOWS LEFT JOIN LOCATIONS L on BUNGALOWS.IDBUNGALOW = L.IDBUNGALOW
WHERE DATEDEBUT<='30/06/2021'
AND DATEFIN>= '01/06/2021'
    )
group by B.NOMBUNGALOW
ORDER BY r desc;

R122
SELECT S.NOMSERVICE, COUNT(P2.IDSERVICE) FROM SERVICES S JOIN (SELECT P.IDSERVICE FROM PROPOSER P
GROUP BY P.IDBUNGALOW
HAVING COUNT(IDBUNGALOW)=1) P2 on S.IDSERVICE = P2.IDSERVICE
group by S.NOMSERVICE


